workflows:
  android-google-play:
    name: Publish Android to Google Play
    environment:
      flutter: stable
      java: 17
      groups:
        - keystore_credentials
        - google_play_credentials
    scripts:
      - name: Clean build directories
        script: |
          flutter clean
          rm -rf ~/.gradle/caches/*/fileHashes
      - name: Get dependencies
        script: flutter pub get
      - name: Build app bundle
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT
        track: internal
      email:
        recipients:
          - mkeparkapp@gmail.com
